[package]
name = "harness-storage-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
harness-session = { path = "../harness-session" }
harness-types = { path = "../harness-types" }

[dev-dependencies]
futures = "0.3"
